import pytest
from pytest import approx

# Import functions from my main file
from water_flow import (
    water_column_height,
    pressure_gain_from_water_height,
    pressure_loss_from_pipe,
    pressure_loss_from_fittings,
    reynolds_number,
    pressure_loss_from_pipe_reduction,
    convert_kpa_to_psi
)


def test_water_column_height() -> None:
    """Verifies water_column_height calculations based on tower and tank height configurations."""
    # Test cases: (tower_height, tank_height, expected_result)
    assert water_column_height(0.0, 0.0) == approx(0.0)
    assert water_column_height(0.0, 10.0) == approx(7.5)
    assert water_column_height(25.0, 0.0) == approx(25.0)
    assert water_column_height(48.3, 12.8) == approx(57.9)


def test_pressure_gain_from_water_height() -> None:
    """Verifies the standard hydrostatic pressure gain generated by water columns."""
    # Test cases: (height, expected_pressure)
    assert pressure_gain_from_water_height(0.0) == approx(0.000, abs=0.001)
    assert pressure_gain_from_water_height(30.2) == approx(295.628, abs=0.001)
    assert pressure_gain_from_water_height(50.0) == approx(489.450, abs=0.001)


def test_pressure_loss_from_pipe() -> None:
    """Verifies friction losses through straight segments using varying pipe dimensions."""
    # Test cases: (pipe_diameter, pipe_length, friction_factor, fluid_velocity, expected_loss)
    assert pressure_loss_from_pipe(0.048692, 0.00, 0.018, 1.75) == approx(0.000, abs=0.001)
    assert pressure_loss_from_pipe(0.048692, 200.00, 0.000, 1.75) == approx(0.000, abs=0.001)
    assert pressure_loss_from_pipe(0.048692, 200.00, 0.018, 0.00) == approx(0.000, abs=0.001)
    assert pressure_loss_from_pipe(0.048692, 200.00, 0.018, 1.75) == approx(-113.008, abs=0.001)
    assert pressure_loss_from_pipe(0.048692, 200.00, 0.018, 1.65) == approx(-100.462, abs=0.001)
    assert pressure_loss_from_pipe(0.286870, 1000.00, 0.013, 1.65) == approx(-61.576, abs=0.001)
    assert pressure_loss_from_pipe(0.286870, 1800.75, 0.013, 1.65) == approx(-110.884, abs=0.001)


def test_pressure_loss_from_fittings() -> None:
    """Verifies turbulent pressure drop constants occurring across pipe intersections."""
    # Test cases: (fluid_velocity, quantity_fittings, expected_loss)
    assert pressure_loss_from_fittings(0.00, 3) == approx(0.000, abs=0.001)
    assert pressure_loss_from_fittings(1.65, 0) == approx(0.000, abs=0.001)
    assert pressure_loss_from_fittings(1.65, 2) == approx(-0.109, abs=0.001)
    assert pressure_loss_from_fittings(1.75, 2) == approx(-0.122, abs=0.001)
    assert pressure_loss_from_fittings(1.75, 5) == approx(-0.306, abs=0.001)


def test_reynolds_number() -> None:
    """Verifies correct execution of non-dimensional fluid mechanics flow states."""
    # Test cases: (hydraulic_diameter, fluid_velocity, expected_reynolds)
    assert reynolds_number(0.048692, 0.00) == approx(0, abs=1)
    assert reynolds_number(0.048692, 1.65) == approx(80069, abs=1)
    assert reynolds_number(0.048692, 1.75) == approx(84922, abs=1)
    assert reynolds_number(0.286870, 1.65) == approx(471729, abs=1)
    assert reynolds_number(0.286870, 1.75) == approx(500318, abs=1)


def test_pressure_loss_from_pipe_reduction() -> None:
    """Verifies restriction losses through narrowing junctions."""
    # Test cases: (larger_diameter, fluid_velocity, reynolds_number, smaller_diameter, expected_loss)
    assert pressure_loss_from_pipe_reduction(0.28687, 0.00, 1, 0.048692) == approx(0.000, abs=0.001)
    assert pressure_loss_from_pipe_reduction(0.28687, 1.65, 471729, 0.048692) == approx(-163.744, abs=0.001)
    assert pressure_loss_from_pipe_reduction(0.28687, 1.75, 500318, 0.048692) == approx(-184.182, abs=0.001)


def test_convert_kpa_to_psi() -> None:
    """Verifies the custom kPa to PSI metric conversion accuracy."""
    # Test 0 kPa is 0 PSI
    assert convert_kpa_to_psi(0.0) == approx(0.0, abs=0.01)
    # Test 100 kPa is roughly 14.50 psi
    assert convert_kpa_to_psi(100.0) == approx(14.50, abs=0.01)
    # Test the target solution benchmark of 158.7 kPa
    assert convert_kpa_to_psi(158.7) == approx(23.02, abs=0.01)


# This Calls the main function that is part of pytest so that the
# computer will execute the test functions in this file.
pytest.main(["-v", "--tb=line", "-rN", __file__])